### 概念：将一维数组称之为秩为 1 的数组，二维数组称为秩为 2 的数组；  .shape 属性获取 ndarray 的形状。shape 属性返回一个由 n 个正整数（用于指定每个维度的大小）组成的元组。

In [1]:
import numpy as np
x = np.array([1,2,3])
y = np.array([1.0,2.2,3.4],dtype = np.int64)

# np.save('my_array',x)

### 1.函数 np.zeros(shape) 会创建一个全是 0 并且为给定形状的 ndarray

In [2]:
x = np.zeros((3,4))
print('x = \n',x)

x = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


###  2. np.ones() 函数会用一个参数来指定你要创建的 ndarray 的形状

In [3]:
y = np.ones((3,2),dtype = np.int64)
print('y = \n',y)

y = 
 [[1 1]
 [1 1]
 [1 1]]


### 3. np.full(shape, constant value) 函数有两个参数。第一个参数是你要创建的 ndarray 的形状，第二个参数是你要向数组中填充的常数值。

In [4]:
z = np.full((2,3),12)
print('z = \n',z)

z = 
 [[12 12 12]
 [12 12 12]]


### 4. 单位矩阵是主对角线上全是 1，其他位置全是 0 的方形矩阵。函数 np.eye(N) 会创建一个对应于单位矩阵的方形 N x N ndarray。因为所有单位矩阵都是方形，因此，np.eye() 函数仅接受一个整数作为参数。

In [5]:
a = np.eye(5)
print('a = \n',a)

a = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5. 使用 np.diag() 函数创建对角矩阵。对角矩阵是仅在主对角线上有值的方形矩阵。np.diag() 函数会创建一个对应于对角矩阵的 ndarray

In [6]:
b = np.diag([10,20,30,40])
print('b = \n',b)

b = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


### 6. np.arange() 函数：np.arange(N) 将创建一个秩为 1 的 ndarray，其中包含从 0 到 N - 1 的连续整数

In [7]:
d = np.arange(10)
print('d = \n',d)

d = 
 [0 1 2 3 4 5 6 7 8 9]


#### 如果传入两个参数，np.arange(start,stop) 将创建一个秩为 1 的 ndarray，其中包含位于半开区间 [start, stop) 内并均匀分布的值。

In [8]:
e = np.arange(5,15)
print('e = \n',e)

e = 
 [ 5  6  7  8  9 10 11 12 13 14]


#### 如果传入三个参数，np.arange(start,stop,step) 将创建一个秩为 1 的 ndarray，其中包含位于半开区间 [start, stop) 内并均匀分布的值，step 表示两个相邻值之间的差。

In [9]:
f = np.arange(0,10,2)
print('f = \n',f)

f = 
 [0 2 4 6 8]


### 7. np.lispace(start,stop,N) 返回 N 个在闭区间 [start, stop] 内均匀分布的数字。在调用 np.linspace() 函数时，必须至少以 np.linspace(start,stop) 的形式传入两个参数。

In [10]:
g = np.linspace(0,25,10)
print('g = \n',g)#返回一个 ndarray，其中包含 10 个在闭区间 [0, 25] 内均匀分布的元素。还可以看出，在此示例中，起始和结束点 0 和 25 都包含在内

g = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [11]:
gg = np.linspace(0,25,10,endpoint=False)# 返回不包含25的ndarray
print('gg = \n',gg)

gg = 
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


### 8. 使用内置函数 np.arange() 和 np.linspace(),与 np.reshape() 函数相结合，创建秩为 2 的任何形状 ndarray,np.reshape(ndarray, new_shape) 函数会将给定 ndarray 转换为指定的 new_shape。

### np.reshape(ndarray, new_shape) 函数会将给定 ndarray 转换为指定的 new_shape。

In [21]:
h = np.arange(20)
# print('h = \n',h)
hh = np.reshape(h, (4,5))
print('hh = \n',hh)

print('x has dimensions:', h.shape)
print('x is an object of type:', type(h))
print('The elements in x are of type:', h.dtype) 

hhh = np.arange(20).reshape((4,5))
print('hhh = \n',hhh)


hh = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x has dimensions: (20,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64
hhh = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### ndarray 中添加元素及删除其中的元素; np.delete(ndarray, elements, axis) 函数删除元素。此函数会沿着指定的轴从给定 ndarray 中删除给定的元素列表。对于秩为 1 的 ndarray，不需要使用关键字 axis。对于秩为 2 的 ndarray，axis = 0 表示选择行，axis = 1 表示选择列。

In [29]:
g = np.array([[1,2,3],[4,5,6],[7,8,9]])
gg = np.delete(g, 0, axis=0)
print("g = \n",gg)

g = 
 [[4 5 6]
 [7 8 9]]


### 向 ndarray 中附加值。我们可以使用 np.append(ndarray, elements, axis) 函数向 ndarray 中附加值。该函数会将给定的元素列表沿着指定的轴附加到 ndarray 中

In [43]:
h = np.array([[1,2],[3,4]])
hh = np.array([[7,8]])
hhh = np.append(h,hh,0)#增加一个新的行，元素为一个ndarray
hhh = np.append(h,[[7],[8]],1)#增加一个新的列，元素为两行一列
print(hhh)

[[1 2 7]
 [3 4 8]]


### 用 np.insert(ndarray, index, elements, axis) 函数向 ndarray 中插入值。此函数会将给定的元素列表沿着指定的轴插入到 ndarray 中，并放在给定的索引前面

In [45]:
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])
print('Original x = ', x) 
x = np.insert(x,2,[3,4])
print('x = ', x)

w = np.insert(Y,1,[4,5,6],axis=0)
# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)
# We print w
print()
print('w = \n', w)
# We print v
print()
print('v = \n', v)

Original x =  [1 2 5 6 7]
x =  [1 2 3 4 5 6 7]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]


### 使用 np.vstack() 函数进行垂直堆叠，或使用 np.hstack() 函数进行水平堆叠。请务必注意，为了堆叠 ndarray，ndarray 的形状必须相符。 

In [46]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]


# ndarray 切片

1. ndarray[start:end] 用于选择在 start 和 end 索引之间的元素；
2. ndarray[start:]用于选择从 start 索引开始直到最后一个索引的所有元素
3. ndarray[:end]用于选择从第一个索引开始直到 end 索引的所有元素。

In [54]:
X = np.arange(20).reshape(4, 5)
print('X = \n', X)
Z = X[1:3,2:5]
# print('Z = \n', Z)
W = X[1:,2:5]

# We print W
print()
# print('W = \n', W)
Y = X[:3,2:5]

# We print Y
print()
# print('Y = \n', Y)
# We select all the elements in the 3rd row
v = X[2,:]
# print('v = ', v)
# We select all the elements in the 3rd column
q = X[:,2]
print('q = ', q)
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]
print('R = \n', R)

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


q =  [ 2  7 12 17]
R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


### np.copy(ndarray) 函数会创建给定 ndarray 的一个副本

### np.diag(ndarray, k=N) 函数会以 N 定义的对角线提取元素。默认情况下，k=0，表示主对角线。k > 0 的值用于选择在主对角线之上的对角线中的元素，k < 0 的值用于选择在主对角线之下的对角线中的元素

In [56]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(25).reshape(5, 5) 
print('X = \n', X) 
# We print the elements in the main diagonal of X
print('z =', np.diag(X)) 
# We print the elements above the main diagonal of X
print('y =', np.diag(X, k=2)) 
# We print the elements below the main diagonal of X
print('w = ', np.diag(X, k=-1))

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
z = [ 0  6 12 18 24]
y = [ 2  8 14]
w =  [ 5 11 17 23]


### 用 np.unique() 函数查找 ndarray 中的唯一元素。np.unique(ndarray) 函数会返回给定 ndarray 中的 唯一元素

In [57]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print('X = \n', X)
print('The unique elements in X are:',np.unique(X))

X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]
The unique elements in X are: [1 2 3 5 8]


In [59]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x,y))#x,y 共有的元素
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))#x中哪些元素y中没有
print('All the elements of x and y:',np.union1d(x,y))#x,y中包含的所有元素

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [65]:
x = np.random.randint(1,11,size=(10,))

# We print x
print('x :', x)
print(np.sort(x))
print('x after sorting:', x)
print(np.sort(np.unique(x)))#去掉重复的值

x : [ 9  6 10  5  4  7  1  3  1  1]
[ 1  1  1  3  4  5  6  7  9 10]
x after sorting: [ 9  6 10  5  4  7  1  3  1  1]
[ 1  3  4  5  6  7  9 10]


In [70]:
X = np.random.randint(1,11,size=(5,5))
print('Original X = \n', X)
# print('X with sorted columns :\n', np.sort(X, axis = 0))
print('X with sorted rows :\n', np.sort(X, axis = 1))

Original X = 
 [[ 8  5  6 10  8]
 [ 6  6  1  2  3]
 [ 5  1  3  7  8]
 [ 9 10  8  3  5]
 [ 8  3  6  5  3]]
X with sorted rows :
 [[ 5  6  8  8 10]
 [ 1  2  3  6  6]
 [ 1  3  5  7  8]
 [ 3  5  8  9 10]
 [ 3  3  5  6  8]]


# 运算符

In [72]:
# We create two rank 1 ndarrays
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


In [74]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print('X = \n', X)
print('Y = \n', Y)

X = 
 [[1 2]
 [3 4]]
Y = 
 [[5.5 6.5]
 [7.5 8.5]]


In [76]:
# We perform basic element-wise operations using arithmetic symbols and functions
# print('X + Y = \n', X + Y)
# print()
# print('add(X,Y) = \n', np.add(X,Y))
# print()
# print('X - Y = \n', X - Y)
# print()
# print('subtract(X,Y) = \n', np.subtract(X,Y))
# print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


In [79]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4])
# We print x
print('x = ', x)
# We apply different mathematical functions to all elements of x
print('EXP(x) =', np.exp(x))
print('SQRT(x) =',np.sqrt(x))
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2

x =  [1 2 3 4]
EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
SQRT(x) = [1.         1.41421356 1.73205081 2.        ]
POW(x,2) = [ 1  4  9 16]
